config/routes.rb
Rails.application.routes.draw do
  get 'draw_tags/new'

  get 'draw_tags/create'

  get 'draw_tags/destroy'

  get 'draw_tags/show'

  get 'draw_tags/edit'

  get 'tags/show'

  get 'tags/new'
  
  #get 'tags/new/:id', to: 'tags#new'
  
  

  get 'tags/create'

  get 'tags/destroy'

  get 'tags/update'

  get 'tags/show'

  get 'tags/new'

  get 'tags/create'

  get 'tags/destroy'

  get 'like_tags/show'

  get 'like_tags/new'

  get 'like_tags/create'

  get 'like_tags/destroy'

  get 'infos/new'
  
  

  get 'infos/show'

  get 'infos/destroy'
  
  

  root to: 'static_pages#redirecto'
  get 'topPage', to:'static_pages#home', as: "top"
  
  get 'sessions/new'
  get 'edit' , to: 'users#edit'
  #サインアップはnewメソッドで処理
  get 'signup',  to: 'users#new'
  get 'fun_signup',  to: 'users#fun_new' ,as:"fun_new"
  get 'select',  to: 'users#select' ,as:"select"
  #ログインはnewメソッドで同じく処理　した後　view/sessions/new.html.erb　で表示
  get 'login' , to: 'sessions#new'
  #post通信で loginが飛んできたら　セッションクラスのクリエイトで処理 view/sessions/create.html.erbで処理
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :snss
  resources :tags
  resources :like_tags
  resources :draw_tags
  resources :infos
  
  get 'users/:id/snss_edit', to: 'snss#edit', as: 'sns_edit'
  get 'users/:id/tags_edit', to: 'tags#new', as: 'tag_edit'
  get 'users/:id/infos_edit', to: 'infos#new', as: 'info_edit'
  

  #セッションを保持するsessionsというモデルを操作するリセットフルなURLを作る
  #sessionsの作成と，セッションの作成，セッションの破棄の3種類だからこうなる
  resources :sessions, only: [:new, :create, :destroy]
  #micropostsを操作するためのURLもつくってちょ
  resources :microposts
  #フォローとフォロー削除を行うURMつくってちょ
  resources :relationships, only: [:create, :destroy]
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def redirecto
    redirect_to top_path
  end
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      
      #自分に関係ある情報提供一覧
      #binding.pry
      @feed_items = current_user.feed_items(params[:page]).includes(:user).order(created_at: :desc)
      #フォロー絵師の最新ニュースフィード
      @infos = current_user.get_news(params[:page]).order(created_at: :desc)
      #@microposts = current_user.following_user
    end
    @rank = Tag.all
      @map = Hash.new
      @rank.each do |tag|
        @map[tag.id] = tag.draw_users.count
      end
    @tags = @map.sort_by{ |_, v| -v }
    #ifを最後に付けることでこの文を実行するかはif文の結果しだいになるとかいう設定（）
  end
end

app/views/static_pages/home.html.erb
<% #今日はここのユーザーごとの表示に注目して作業を進める %>

<div class="container pageContents" style="margin-top:100px">
  
<% if logged_in? && current_user.creator == true %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
      <%= render 'shared/user_info' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>公式更新情報</h3>
      <%= render 'shared/infos' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= render 'shared/tags' %>
    </div>
  </div>
  <%= paginate(@infos) %>
  <%= page_entries_info(@infos) %>
  <% else %>
  <% if logged_in? && current_user.creator == false %>
    <div class="col-md-12">
      <h3>公式更新情報</h3>
      <%= render 'shared/infos' %>
      <%= render 'shared/tags' %>
    </div>
  <% else %>
    <%= render 'shared/tags' %>
  <% end %>
<% end %>
</div>

<% #ログインしてない場合はトップページにも表示する %>
<% unless logged_in? %>
<div style="height:600px;"></div>

<div class="col-sm-4"></div>
<div class="select_box col-sm-4 login_box">
    <span class="col-sm-12 col-xs-12" id="logo2" style="text-align:center;">Moe Creators</span>
    <span class="col-sm-12 col-xs-12" style="text-align:center; font-size:1.2em">創作活動でもっとつながる<br />イラストクリエイターがみつかるSNS</span>
    <%= link_to "一般登録", fun_new_url, class: "btn btn-mini btn-success fun col-sm-12 col-xs-12" %>
    <%= link_to "クリエイター登録", new_user_path, class: "btn btn-mini btn-warning creator col-sm-12 col-xs-12" %>
    <%= link_to "ログイン", login_url, class: "btn btn-mini btn-info select_login col-sm-12 col-xs-12" %>
</div>
<div class="col-sm-4 sita"></div>

<% end %>

app/views/static_pages/home.js.erb
$("#pictures").append("<div class='page'><%= escape_javascript(render('shared/inf', :locals => { :tags => @feed_items.tag_list })) %></div>");