config/routes.rb
Rails.application.routes.draw do
  get 'draw_tags/new'

  get 'draw_tags/create'

  get 'draw_tags/destroy'

  get 'draw_tags/show'

  get 'draw_tags/edit'

  get 'tags/show'

  get 'tags/new'
  
  #get 'tags/new/:id', to: 'tags#new'
  
  

  get 'tags/create'

  get 'tags/destroy'

  get 'tags/update'

  get 'tags/show'

  get 'tags/new'

  get 'tags/create'

  get 'tags/destroy'

  get 'like_tags/show'

  get 'like_tags/new'

  get 'like_tags/create'

  get 'like_tags/destroy'

  get 'infos/new'
  
  

  get 'infos/show'

  get 'infos/destroy'
  
  

  root to: 'static_pages#redirecto'
  get 'topPage', to:'static_pages#home', as: "top"
  
  get 'sessions/new'
  get 'edit' , to: 'users#edit'
  #サインアップはnewメソッドで処理
  get 'signup',  to: 'users#new'
  get 'fun_signup',  to: 'users#fun_new' ,as:"fun_new"
  get 'select',  to: 'users#select' ,as:"select"
  #ログインはnewメソッドで同じく処理　した後　view/sessions/new.html.erb　で表示
  get 'login' , to: 'sessions#new'
  #post通信で loginが飛んできたら　セッションクラスのクリエイトで処理 view/sessions/create.html.erbで処理
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :snss
  resources :tags
  resources :like_tags
  resources :draw_tags
  resources :infos
  
  get 'users/:id/snss_edit', to: 'snss#edit', as: 'sns_edit'
  get 'users/:id/tags_edit', to: 'tags#new', as: 'tag_edit'
  get 'users/:id/infos_edit', to: 'infos#new', as: 'info_edit'
  

  #セッションを保持するsessionsというモデルを操作するリセットフルなURLを作る
  #sessionsの作成と，セッションの作成，セッションの破棄の3種類だからこうなる
  resources :sessions, only: [:new, :create, :destroy]
  #micropostsを操作するためのURLもつくってちょ
  resources :microposts
  #フォローとフォロー削除を行うURMつくってちょ
  resources :relationships, only: [:create, :destroy]
  
end

app/views/shared/_error_messages.html.erb
<% #object=@user  %>
<% if object.errors.any? %>

  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains 
<%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    
<% object.errors.full_messages.each do |msg| %>

      <li>
<%= msg %>
</li>
    
<% end %>

    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>

  <ol class="microposts">
    
<%= render @feed_items %>

  </ol>
<% end %>

app/views/shared/_inf.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
  <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_infos.html.erb
<table class="table table-striped">
    <thead>
      <tr>
        <th colspan="3"  class="col-sm-12">フォローしている絵師の公式ニュース</th>
      </tr>
    </thead>
<tbody>
    
    <% for i in 0..4 %>
    
    <% break if @infos[i]==nil %>
        <tr>
            <% #binding.pry %>
            <% @user = User.find_by(id:@infos[i].user_id) %>
            
            <td rowspan="2" class="col-sm-2">
            <%= 
                if @user[:avatar]==nil 
                    link_to gravatar_for(@user, size: 40), @user
                else 
                    link_to image_tag(@user.avatar,:size => "40x40", :alt => "アイコン") ,user_path(@user)
                end
            %>
            <br />
            <%= link_to @user.name ,user_path(@user) %>
            </td>
            
            <td class="col-sm-6"><%= link_to @infos[i].text,@infos[i].link %></td>
            <% @date = @infos[0].created_at.to_datetime+Rational(9, 24) %>
            <tr>
            <td colspan="2"><%= @date.year.to_s + "年" + @date.month.to_s + "月" + @date.day.to_s + "日"+ @date.hour.to_s + "時" + @date.min.to_s + "分" %>
             </td>
            </tr>
        </tr>
    <% end %>
</tbody>
</table>

app/views/shared/_micropost_form.html.erb
<% #binding.pry %>
<% #------------------本人--------------------- %>
<% if current_user.id == @user.id %>

<% #------------------本人以外--------------------- %>
<% else %>
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "#{@user.name}さんに関する情報の提供しましょう，誹謗中傷や#{@user.name}さんに関係のない情報提供をしないでください" %>
  </div>
  <div class="field" style="display:none;">
    <% #binding.pry %>
    <input id="touser_id" name="touser_id" size="10" type="text" value="<%= @user.id %>" />
  </div>
  <%= f.submit "情報提供する", class: "btn btn-primary" %>
<% end %>
<% end %>

app/views/shared/_tags.html.erb
<div style="font-size:2em; text-align:center;"><hr>今日のピックアップタグ<hr></div>

<a href="tags/show?id=89"><div class="tag_view2 tag_view"><div class="nam">オリジナル</div></div></a>
<a href="tags/show?id=2"><div class="tag_view1 tag_view"><div class="nam">ロリ</div></div></a>
<a href="tags/show?id=17"><div class="tag_view3 tag_view"><div class="nam">和服</div></div></a>
<a href="tags/show?id=143"><div class="tag_view4 tag_view"><div class="nam">制服</div></div></a>
<a href="tags/show?id=161"><div class="tag_view5 tag_view"><div class="nam">一度見たら忘れない</div></div></a>
<a href="tags/show?id=43"><div class="tag_view6 tag_view mobile_only"><div class="nam">水着</div></div></a>




<% for i in 0..100 %>
        <% break if @tags[i]==nil %>
        <%= link_to "#{Tag.find_by(id:@tags[i][0]).name}(#{@tags[i][1]})", tags_show_path(id: @tags[i][0]),class:"btn-success btn" %>
        <% i += 1 %>
        <% if i % 3 == 0 && @tags[i]!=nil %>
        <% end %>
<% end %>
    

app/views/shared/_tome_micropost.html.erb
<table class="table table-striped">
    <thead>
      <tr>
        <th colspan="1">ファンからの情報</th>
      </tr>
    </thead>
<tbody>
    <% #binding.pry %>
    <% if current_user.id == @user.id %>
        <% for i in 0..4 %>
        <% break if @microposts[i]==nil %>
            <tr><td><%= @microposts[i].content %></td>
            <% #binding.pry %>
            <td><%= link_to '削除',micropost_path(id: @microposts[i].id) , :method => :delete %></td></tr>
        <% end %>
    <% else %>
        <% for i in 0..4 %>
        <% break if @microposts[i]==nil %>
            <tr><td><%= @microposts[i].content %></td></tr>
        <% end %>
    <% end %>
</tbody>
</table>

app/views/shared/_user_info.html.erb
<div class="col-sm-12" style="text-align:center;">
<%= 
if current_user[:avatar]==nil 
    link_to gravatar_for(current_user, size: 90), current_user
else 
    link_to (image_tag current_user.avatar, :size => '150'), current_user
end
%>
</div>


<div class="col-sm-12" style="text-align:center">
    <hr>
    <%= link_to "マイページ", current_user,class:"btn btn-info col-ms-4" %>
    <%= link_to "フォロー：" +  current_user.following_users.count.to_s, following_user_url(current_user), class: "btn btn-primary col-ms-4" %>
    <%= link_to "フォロワ：" +  current_user.follower_users.count.to_s, followers_user_url(current_user), class: "btn btn-primary col-ms-4" %>
</div>

app/views/shared/_user_info2.html.erb
<div class="col-sm-12" style="text-align:center;">
<%= 
if @user[:avatar]==nil 
    link_to gravatar_for(@user, size: 90), @user
else 
    link_to (image_tag @user.avatar, :size => '150'), @user
end
%>
</div>


<div class="col-sm-12" style="text-align:center">
    <hr>
    <%= link_to "マイページ", @user,class:"btn btn-info col-ms-4" %>
    <%= link_to "フォロー：" +  @user.following_users.count.to_s, following_user_url(@user), class: "btn btn-primary col-ms-4" %>
    <%= link_to "フォロワ：" +  @user.follower_users.count.to_s, followers_user_url(@user), class: "btn btn-primary col-ms-4" %>
</div>

app/views/shared/_users.html.erb
 <div style="text-align:center; font-size:2em;"><hr><%= @tag.name %>を描く絵師<div>
    <% for i in 0..100 %>
    <hr />
    <% #ユーザーアバター %>
    <div class="col-xs-3 myprof">
    <% break if @users[i]==nil %>
    <%= 
      if @users[i][:avatar]==nil
        link_to gravatar_for(@users[i]), user_path(id:@users[i])
      else 
        link_to image_tag(@users[i].avatar,:style => "", :style => "width:100%;height:auto;") , user_path(id:@users[i])
    end %>
    <br />
    <%= link_to @users[i].name , user_path(id:@users[i]),:class => "string" %><br/>
    </div>
    
    <% #タグ %>
    
    <div class="col-xs-9">
    <% if @users[i].work != nil %>
      <%= image_tag(@users[i].work,'data-action' => "zoom", :style => "width:100%;height:auto;") %> 
    <% end %>
    </div>
    <div class="col-xs-12 mobile_none">
      <% #最新情報 %>
      <% @info = Info.where(user_id:@users[i].id).last %>
      <% if @info != nil %>
        <% if @info.text != nil && @info.link != nil %>
          <%= link_to @info.text ,@info.link,:class=>"btn btn-success",:style=>"width:70%;" %>
         <% end %>
      <% end %>
    </div>
    


  
       <% if logged_in? && current_user.id != @users[i].id %>
       <% @user = @users[i] %>
        <div id=<%= "follow_form#{@user.id}"%>>
          <% #binding.pry %>
             <% if current_user.following?(@users[i]) %>
              <%= render 'users/unfollow' %>
             <% else %>
              <%= render 'users/follow' %>
            <% end %>
        </div>
      <% elsif !logged_in? && i==0 %>
         <%= link_to "会員登録してフォロー", select_path, class: "btn btn-mini btn-success fun" %>
      <% end %>
  
<% end %>