config/routes.rb
Rails.application.routes.draw do
  get 'draw_tags/new'

  get 'draw_tags/create'

  get 'draw_tags/destroy'

  get 'draw_tags/show'

  get 'draw_tags/edit'

  get 'tags/show'

  get 'tags/new'
  
  #get 'tags/new/:id', to: 'tags#new'
  
  

  get 'tags/create'

  get 'tags/destroy'

  get 'tags/update'

  get 'tags/show'

  get 'tags/new'

  get 'tags/create'

  get 'tags/destroy'

  get 'like_tags/show'

  get 'like_tags/new'

  get 'like_tags/create'

  get 'like_tags/destroy'

  get 'infos/new'
  
  

  get 'infos/show'

  get 'infos/destroy'
  
  

  root to: 'static_pages#redirecto'
  get 'topPage', to:'static_pages#home', as: "top"
  
  get 'sessions/new'
  get 'edit' , to: 'users#edit'
  #サインアップはnewメソッドで処理
  get 'signup',  to: 'users#new'
  get 'fun_signup',  to: 'users#fun_new' ,as:"fun_new"
  get 'select',  to: 'users#select' ,as:"select"
  #ログインはnewメソッドで同じく処理　した後　view/sessions/new.html.erb　で表示
  get 'login' , to: 'sessions#new'
  #post通信で loginが飛んできたら　セッションクラスのクリエイトで処理 view/sessions/create.html.erbで処理
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :snss
  resources :tags
  resources :like_tags
  resources :draw_tags
  resources :infos
  
  get 'users/:id/snss_edit', to: 'snss#edit', as: 'sns_edit'
  get 'users/:id/tags_edit', to: 'tags#new', as: 'tag_edit'
  get 'users/:id/infos_edit', to: 'infos#new', as: 'info_edit'
  

  #セッションを保持するsessionsというモデルを操作するリセットフルなURLを作る
  #sessionsの作成と，セッションの作成，セッションの破棄の3種類だからこうなる
  resources :sessions, only: [:new, :create, :destroy]
  #micropostsを操作するためのURLもつくってちょ
  resources :microposts
  #フォローとフォロー削除を行うURMつくってちょ
  resources :relationships, only: [:create, :destroy]
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    validates :name, presence: true, length: { maximum: 15 }
    #user.draws = 中間テーブルが取れる　<=　Drawモデルからuser_idで取得する class_nameは省略可能
    has_many :draws, class_name: "Draw" , foreign_key: "tag_id", dependent: :destroy
    #user.draw_tags ＝　タグ一覧が取れる
    #定義済みの中間テーブル（draws）のtagを取得する
    has_many :draw_users, through: :draws, source: :user
    
    has_many :likes, class_name: "Like", foreign_key: "tag_id", dependent: :destroy
    has_many :like_users , through: :likes, source: :user
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    if params["id"] != nil
      @tag = Tag.find_by(id: params["id"])
      @user = @tag.draw_users
      @map = Hash.new
      @user.each do |user|
        @map[user] = user.follower_users.count
      end
      @user = @map.sort_by{ |_, v| -v }
      
      @users = []
      i = 0
      @user.each do |user|
        @users[i] = @user[i][0]
        i = i + 1
      end
      
      @user = @users.first
    else
      #特にid指定がない場合はフォロワーが多いタグから順番に表示する
      #タグidが指定されている場合はそのタグを登録している絵師さんを人気順に30こ表示する
      @rank = Tag.all
      @map = Hash.new
      @rank.each do |tag|
        @map[tag.id] = tag.draw_users.count
      end
      @tags = @map.sort_by{ |_, v| -v }
    end
  end
  def new
    #背景を入れたいので@userを定義
    @user = current_user
    @tag = Tag.new
    #binding.pry
    @tags = current_user.draw_tags
  end

  def create
    #Paramsの中から値を取得．sns_paramsでSns型に当てはまらない不要なデータ型を削除する
    #binding.pry
    @tag = Tag.find_by(name: params["tag"]["name"])
    @tag = Tag.new(sns_params) if @tag == nil
    if @tag.save
      current_user.draw_tags_add(@tag)
      #タグを保存できたらdraw_Tag中間テーブルにそのタグを登録した絵師のidとタグのidをひも付けておく
      flash[:success] = "#{@tag.name}を登録しました"
      redirect_to request.referer
    else
      flash[:success] = "#{@tag.name}　15文字いないで入力してください"
      redirect_to request.referer
    end
  end

  def destroy
    @del = Tag.find_by(id: params["del_id"])
    if current_user==nil
      flash[:success] = "この操作を行うためには再度ログインしてください"
      redirect_to root_path
    else
      current_user.draw_tags_del(@del)
      redirect_to request.referer
    end
  end

  def update
  end
  
  def sns_params
    params.require(:tag).permit(:name)
  end
end

app/views/tags/_new_tag.html.erb
<%= form_for(@tag) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
        
        <label for="message_name" class="control-label col-md-12">タグ名</label>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <%= f.submit "タグを追加", class: "btn btn-large btn-primary" %>
<% end %>

app/views/tags/_now_tag.html.erb
<div style="font-size:1.5em; text-align:center;">登録タグの削除<div>
<% for i in 0..100 %>
    <% break if @tags[i]==nil %>
    <% #link_to @tags[i].name, tags_show_path(id: @tags[i].id) %>
    <%= link_to @tags[i].name ,tags_destroy_path(:del_id => @tags[i].id), :method => :delete , :class => 'btn btn-danger col-xs-12 col-lg-4  col-sm-6',:style=>"margin-top:2px;", data: {confirm: "#{@tags[i].name}を本当に削除しますか？"} %>
<% end %>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/new.html.erb
<div style="text-align: center; width:100%; font-size:20px;"><br />描くタグの登録</div>
<%= render 'new_tag' %>
<hr />
<%= render 'now_tag' %>

app/views/tags/show.html.erb
<% if params[:id]!=nil %>
    <%= render 'shared/users' %>
<% else %>
    <%= render 'shared/tags' %>
<% end %>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>