config/routes.rb
Rails.application.routes.draw do
  get 'draw_tags/new'

  get 'draw_tags/create'

  get 'draw_tags/destroy'

  get 'draw_tags/show'

  get 'draw_tags/edit'

  get 'tags/show'

  get 'tags/new'
  
  #get 'tags/new/:id', to: 'tags#new'
  
  

  get 'tags/create'

  get 'tags/destroy'

  get 'tags/update'

  get 'tags/show'

  get 'tags/new'

  get 'tags/create'

  get 'tags/destroy'

  get 'like_tags/show'

  get 'like_tags/new'

  get 'like_tags/create'

  get 'like_tags/destroy'

  get 'infos/new'
  
  

  get 'infos/show'

  get 'infos/destroy'
  
  

  root to: 'static_pages#redirecto'
  get 'topPage', to:'static_pages#home', as: "top"
  
  get 'sessions/new'
  get 'edit' , to: 'users#edit'
  #サインアップはnewメソッドで処理
  get 'signup',  to: 'users#new'
  get 'fun_signup',  to: 'users#fun_new' ,as:"fun_new"
  get 'select',  to: 'users#select' ,as:"select"
  #ログインはnewメソッドで同じく処理　した後　view/sessions/new.html.erb　で表示
  get 'login' , to: 'sessions#new'
  #post通信で loginが飛んできたら　セッションクラスのクリエイトで処理 view/sessions/create.html.erbで処理
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :snss
  resources :tags
  resources :like_tags
  resources :draw_tags
  resources :infos
  
  get 'users/:id/snss_edit', to: 'snss#edit', as: 'sns_edit'
  get 'users/:id/tags_edit', to: 'tags#new', as: 'tag_edit'
  get 'users/:id/infos_edit', to: 'infos#new', as: 'info_edit'
  

  #セッションを保持するsessionsというモデルを操作するリセットフルなURLを作る
  #sessionsの作成と，セッションの作成，セッションの破棄の3種類だからこうなる
  resources :sessions, only: [:new, :create, :destroy]
  #micropostsを操作するためのURLもつくってちょ
  resources :microposts
  #フォローとフォロー削除を行うURMつくってちょ
  resources :relationships, only: [:create, :destroy]
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse mobile_none">
  <div class="container">
    <%= link_to "Moe Creatores", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "タグで探す", tags_show_url %></li>
        
        <% #binding.pry %>
        <% if logged_in? && current_user.creator == true %>
          <% #ユーザーメニュー  %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              ユーザー <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "フォロー", following_user_url(current_user) %></li>
              <li><%= link_to "フォロワー", followers_user_url(current_user) %></li>
            </ul>
          </li>
          
          <% #アカウントメニュー  %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "基本設定", edit_user_path(current_user) %></li>
              <li><%= link_to 'SNS設定', sns_edit_path(current_user) %></li>
              <li><%= link_to '公式ニュース設定', info_edit_path(current_user) %></li>
              <li><%= link_to '描くイラストのタグ設定', tag_edit_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <% if logged_in? %>
            <li><%= link_to "フォロー", following_user_url(current_user) %></li>
            <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "会員登録", select_path %></li>
            <li><%= link_to "ログイン", login_path %></li>
          <% end %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_headerm.html.erb
<header class="navbar navbar-fixed-top navbar-inverse mobile_true">
  <div class="container">
    <%= link_to "Moe Creatores", root_path, id: "logo" %>
    <nav>
      <ul class="navbar-right navbar-nav">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "タグで探す", tags_show_url %></li>
        
        
        <% #binding.pry %>
        <% if logged_in? && current_user.creator == true %>
          <% #ユーザーメニュー  %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              ユーザー <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "フォロー", following_user_url(current_user) %></li>
              <li><%= link_to "フォロワー", followers_user_url(current_user) %></li>
            </ul>
          </li>
          
          <% #アカウントメニュー  %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "基本設定", edit_user_path(current_user) %></li>
              <li><%= link_to 'SNS設定', sns_edit_path(current_user) %></li>
              <li><%= link_to '公式ニュース設定', info_edit_path(current_user) %></li>
              <li><%= link_to '描くイラストのタグ設定', tag_edit_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <% if logged_in? %>
            <li><%= link_to "フォロー", following_user_url(current_user) %></li>
            <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "会員登録", select_path %></li>
            <li><%= link_to "ログイン", login_path %></li>
          <% end %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>もえくり</title>
  <meta name=viewport content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  
  <%= csrf_meta_tags %>
  <script type="text/javascript">  
  $(function(){
    $('.bgslideshow img:gt(0)').hide();
    setInterval(function() {
      $('.bgslideshow :first-child').fadeOut(5000)  
        .next('img').fadeIn(5000)  
      .end().appendTo('.bgslideshow');  
    },30000);
  });  
</script>

</head>
<% if @user != nil && !request.url.include?("users/new") && !request.url.include?("fun") %>
    <% if @user[:picture] != nil %>
      <% #ある特定の人のページで @user=nil  で壁紙設定してる %>
        <% if request.user_agent.include?("Android") || request.user_agent.include?("iPhone")|| request.user_agent.include?("iPad")|| request.user_agent.include?("Kindle") %>
          <body>
          <div class="bgslideshow">
            <%= image_tag("m1.jpg",:class=>"mobile_pic") %>
            <%= image_tag("m2.jpg",:class=>"mobile_pic") %>
            <%= image_tag("m3.jpg",:class=>"mobile_pic") %>
          </div>  
          <% else %>
            <body class="allbody" background="<%= @user.picture %>">
          <% end %>
    <% #@userが壁紙設定してない %>
    <% else %>
      <body>
        <% if request.user_agent.include?("Android") || request.user_agent.include?("iPhone")|| request.user_agent.include?("iPad")|| request.user_agent.include?("Kindle") %>
          <div class="bgslideshow">
            <%= image_tag("m1.jpg",:class=>"mobile_pic") %>
            <%= image_tag("m2.jpg",:class=>"mobile_pic") %>
            <%= image_tag("m3.jpg",:class=>"mobile_pic") %>
          </div>  
        <% else %>
          <div class="bgslideshow">
            <%= image_tag("1.jpg") %>
            <%= image_tag("2.jpg") %>
            <%= image_tag("3.jpg") %>
          </div>
        <% end %>
    <% end %>
<% else %>

  <% if logged_in? %>
    <% if current_user[:bg] != nil %>
      <% #ログインしてて壁紙設定してる %>
        <% if request.user_agent.include?("Android") || request.user_agent.include?("iPhone")|| request.user_agent.include?("iPad")|| request.user_agent.include?("Kindle") %>
          <body>
          <div class="bgslideshow">
            <%= image_tag("m1.jpg",:class=>"mobile_pic") %>
            <%= image_tag("m2.jpg",:class=>"mobile_pic") %>
            <%= image_tag("m3.jpg",:class=>"mobile_pic") %>
          </div>  
          <% else %>
        <body class="allbody" background="<%= current_user.bg %>">
      <% end %>
    <% #ログインしてるけど壁紙設定してないならデフォルト %>
    <% else %>
        <% if request.user_agent.include?("Android") || request.user_agent.include?("iPhone")|| request.user_agent.include?("iPad")|| request.user_agent.include?("Kindle") %>
          <div class="bgslideshow">
            <%= image_tag("m1.jpg",:class=>"mobile_pic") %>
            <%= image_tag("m2.jpg",:class=>"mobile_pic") %>
            <%= image_tag("m3.jpg",:class=>"mobile_pic") %>
          </div>  
        <% else %>
          <div class="bgslideshow">
            <%= image_tag("1.jpg") %>
            <%= image_tag("2.jpg") %>
            <%= image_tag("3.jpg") %>
          </div>
        <% end %>
    <% end %>
  
  <% #ログインしてないならデフォルト壁紙 %>
  <% else %>
    <% if request.user_agent.include?("Android") || request.user_agent.include?("iPhone")|| request.user_agent.include?("iPad")|| request.user_agent.include?("Kindle") %>
      <div class="bgslideshow">
        <%= image_tag("m1.jpg",:class=>"mobile_pic") %>
        <%= image_tag("m2.jpg",:class=>"mobile_pic") %>
        <%= image_tag("m3.jpg",:class=>"mobile_pic") %>
      </div>  
    <% else %>
      <div class="bgslideshow">
        <%= image_tag("1.jpg") %>
        <%= image_tag("2.jpg") %>
        <%= image_tag("3.jpg") %>
      </div>
    <% end %>
  <% end %>
<% end %>
 <%= render 'layouts/header' %>
 <%= render 'layouts/headerm' %>
 <% if request.url.include?("select")||request.url.include?("topPage") %>
  <div class="container" style="overflow-y:hidden;">
 <% else %>
  <div class="container pageContents">
 <% end %>
    <% flash.each do |message_type, message| %> 
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>